export const PLANT_DETAIL         = 'PLANT_DETAIL'
export const PLANT_DETAIL_LOADING = 'PLANT_DETAIL_LOADING'

export const FETCH_PLANT_OVERVIEW_ACTION         = 'FETCH_PLANT_OVERVIEW_ACTION'
export const FETCH_PLANT_OVERVIEW_LOADING_ACTION = 'FETCH_PLANT_OVERVIEW_LOADING_ACTION'