version: '2'
services:
  api-hub-ui:
    container_name: api-hub-monitoring
    build: .
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    environment:
      - REACT_APP_BASE_URL=http://18.142.181.118:4000