export const FETCHING_DETAIL_DATAHUB = "FETCHING_DETAIL_DATAHUB"
export const FETCHING_DETAIL_DATAHUB_LOADING = "FETCHING_DETAIL_DATAHUB_LOADING"

export const UPDATE_DATAHUB = 'UPDATE_DATAHUB' 
export const UPDATE_DATAHUB_LOADING = 'UPDATE_DATAHUB_LOADING' 

export const FETCHING_LIST_TAG_DATAHUB = 'FETCHING_LIST_TAG_DATAHUB'
export const FETCHING_LIST_TAG_DATAHUB_LOADING = 'FETCHING_LIST_TAG_DATAHUB_LOADING'

export const ADD_TAG = 'ADD_TAG' 
export const ADD_TAG_LOADING = 'ADD_TAG_LOADING' 

export const REMOVE_TAG = 'REMOVE_TAG'
export const REMOVE_TAG_LOADING = 'REMOVE_TAG_LOADING'
