export const FETCHING_DETAIL_DATAHUB = "FETCHING_DETAIL_DATAHUB"
export const FETCHING_DETAIL_DATAHUB_LOADING = "FETCHING_DETAIL_DATAHUB_LOADING"

export const UPDATE_DATAHUB = 'UPDATE_DATAHUB' 
export const UPDATE_DATAHUB_LOADING = 'UPDATE_DATAHUB_LOADING' 

export const FETCHING_LIST_TAG_DATAHUB = 'FETCHING_LIST_TAG_DATAHUB'
export const FETCHING_LIST_TAG_DATAHUB_LOADING = 'FETCHING_LIST_TAG_DATAHUB_LOADING'

export const ADD_TAG = 'ADD_TAG' 
export const ADD_TAG_LOADING = 'ADD_TAG_LOADING' 

export const REMOVE_TAG = 'REMOVE_TAG'
export const REMOVE_TAG_LOADING = 'REMOVE_TAG_LOADING'

export const DOWNLOAD_CONFIG = 'DOWNLOAD_CONFIG'
export const DOWNLOAD_CONFIG_LOADING = 'DOWNLOAD_CONFIG_LOADING'

export const CONNECT_DATA_HUB = 'CONNECT_DATA_HUB'
export const CONNECT_DATA_HUB_LOADING = 'CONNECT_DATA_HUB_LOADING'

export const DISCONNECT_DATA_HUB = 'DISCONNECT_DATA_HUB'
export const DISCONNECT_DATA_HUB_LOADING = 'DISCONNECT_DATA_HUB_LOADING'

export const FECHING_CONNECT_DATA_HUB = 'FECHING_CONNECT_DATA_HUB'
export const FECHING_CONNECT_DATA_HUB_LOADING = 'FECHING_CONNECT_DATA_HUB_LOADING'

export const DELETE_TAG_CONFIG = 'DELETE_TAG_CONFIG'
export const DELETE_TAG_CONFIG_LOADING = 'DELETE_TAG_CONFIG_LOADING'