export const FETCHING_LIST_ALL_DEVICE = 'FETCHING_LIST_ALL_DEVICE'
export const FETCHING_LIST_ALL_DEVICE_LOADING = 'FETCHING_LIST_ALL_DEVICE_LOADING'

export const DOWNLOAD_CONFIG = 'DOWNLOAD_CONFIG'
export const DOWNLOAD_CONFIG_LOADING = 'DOWNLOAD_CONFIG_LOADING'