apiVersion: v1
kind: Service
metadata:
  name: api-hub-ui-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3010
      targetPort: 3010
      nodePort: 30100
  selector:
    component: api-hub-ui