apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    # - host: grails.se.slave04.internal
    - http:
        paths:
          - pathType: Prefix 
            path: /api-source/?(.*)
            backend:
              service:
                name: api-hub-ui-service
                port: 
                  number: 3010