export const FETCHING_LIST_DEVICE = 'FETCHING_LIST_DEVICE'
export const FETCHING_DETAIL_DEVICE_LOADING = 'FETCHING_DETAIL_DEVICE_LOADING'
export const FETCHING_DETAIL_DEVICE = 'FETCHING_DETAIL_DEVICE'
export const FETCHING_LIST_DEVICE_LOADING = 'FETCHING_LIST_DEVICE_LOADING'
export const CREATE_DEVICE = 'CREATE_DEVICE'
export const CREATE_DEVICE_LOADING = 'CREATE_DEVICE_LOADING'

export const UPDATE_DEVICE = 'UPDATE_DEVICE' 
export const UPDATE_DEVICE_LOADING = 'UPDATE_DEVICE_LOADING' 

export const DELETE_DEVICE = 'DELETE_DEVICE'
export const DELETE_DEVICE_LOADING = 'DELETE_DEVICE_LOADING'