export const FETCHING_LIST_DEVICE = 'FETCHING_LIST_DEVICE'
export const FETCHING_LIST_DEVICE_LOADING = 'FETCHING_LIST_DEVICE_LOADING'
export const CREATE_DEVICE = 'CREATE_DEVICE'
export const CREATE_DEVICE_LOADING = 'CREATE_DEVICE_LOADING'