export const FETCHING_LIST_APISOURCE = "FETCHING_LIST_APISOURCE"
export const FETCHING_LIST_APISOURCE_LOADDING = "FETCHING_LIST_APISOURCE_LOADDING"
export const CREATE_DEVICE = 'CREATE_DEVICE'
export const CREATE_DEVICE_LOADING = 'CREATE_DEVICE_LOADING'
export const DELETE_DEVICE = 'DELETE_DEVICE'
export const DELETE_DEVICE_LOADING = 'DELETE_DEVICE_LOADING'
