export const FETCHING_LIST_APISOURCE = "FETCHING_LIST_APISOURCE"
export const FETCHING_LIST_APISOURCE_LOADDING = "FETCHING_LIST_APISOURCE_LOADDING"
export const CREATE_APISOURCE = 'CREATE_APISOURCE'
export const CREATE_APISOURCE_LOADING = 'CREATE_APISOURCE_LOADING'
export const DELETE_APISOURCE = 'DELETE_APISOURCE'
export const DELETE_APISOURCE_LOADING = 'DELETE_APISOURCE_LOADING'
